### ISSUE TITLE
LCD 12864 is not wrk in mother board KMS_GEN_L V2.1

### ISSUE THREAD

**Issue by qusai210** [makerbase-mks/MKS-H43-firmware#2]
my lcd .
There is no electricity reaching for it when the mother board on 
 ,and i used marlin code 
can you help me?
![134561922_3620350364726625_2013085135601210014_o](https://user-images.githubusercontent.com/72452941/103413404-439eee00-4b2e-11eb-81ba-7c74cf3f46e3.jpg)

**Comment by mks-viva** [comment]
Hi! Please refer this question to the MKS Gen_L project, i will close this issues.
You need to connect the buckle to the MKS Gen_L motherboard at 180 degrees
